title: My Software Development Blog
description: A simple blog hosted on GitHub Pages
markdown: kramdown
baseurl: "/blog"
url: "https://yellowmoss.github.io"
permalink: /blog/:year/:month/:day/:title
